apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway

spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: marinastancu/gateway:latest
          ports:
            - containerPort: 5000
          env:
            - name: Auth0__Domain
              valueFrom:
                secretKeyRef:
                  name: auth0
                  key: DOMAIN
            - name: Auth0__Audience
              valueFrom:
                secretKeyRef:
                  name: auth0
                  key: AUDIENCE
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress

spec:
  ingressClassName: nginx
  rules:
  # - host: frankensound.test
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 80