apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    job: gateway-job
    app: gateway-service
spec:
  selector:
    app: gateway
  type: ClusterIP
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP